"""Add cached stats columns

Revision ID: ec38f1537732
Revises: 04cdc40ad275
Create Date: 2026-06-10 19:17:04.059950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec38f1537732'
down_revision = '04cdc40ad275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_elo', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_tier', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('stats_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stats_updated_at')
        batch_op.drop_column('last_tier')
        batch_op.drop_column('last_elo')

    # ### end Alembic commands ###
